### ISSUE TITLE
DB(localStorage)設計

### ISSUE THREAD

**Issue by pachikuriii** [pachikuriii/yametara#3]
DBを使用しないため、localstrageの構造を検討しました。

Key：`userStatus`
Value：
```json
{
  "started": true,
  "retirement_year": 2022,
  "retirement_month": 12,
  "retirement_date": 31,
  "retirement_reason": 1, // ※
  "re_employment": false,
  "age": 1,  // ※
  "post_code": 1234567,
  "family": false,
  "emp_ins_last_two_years": 3,  // ※
  "emp_ins_total": 2,  // ※
  "health_ins_last_two_month": true,
  "health_ins_after_retirement": 2,  // ※
  "tax": 2,  // ※
  "question": "q10"
}

 // ※の部分はユーザー回答の選択肢に番号を振る想定
```

**Comment by betachelsea** [comment]
DBを使用しない == 永続化しない、という判断の様子かなと思って拝見しました :eyes: 
いくつか思ったことについて共有します！

- 退職予定日が  `2022` 、`12` 、 `31` で分けて保存されていますが、日付として取り扱うならまとめておいたほうが取り出しやすくて簡便なのではないかと思いました。
- post_code(郵便番号)が入っていますが、お住まいの番地なので、これを重要な個人情報と考えるか否かで取り扱いが変わってきそうです。自分はlocalStorageはあんまり安全性を信用していないので(※)郵便番号を取り扱うのはちょっと躊躇しそうです。郵便番号はresultのどの部分に影響するのか、もうちょっと仕様を深掘りして教えていただけますか？ :eyes:  (そのご回答によってはもう少し実装に突っ込んだ形のレビューができそうかなと考えています)
- question というのは現在表示している question 番号、という認識で良いですか？ result ページのとき、ここの値がどうなるか決めておいたほうが迷わずにすみそうです。
- (ペーパープロトタイプを見て) 「シュミレーション」という表記がありましたが、「シミュレーション」( `simulation` ) のためご注意ください〜 :pray: 


※参考
- [HTML5のLocal Storageを使ってはいけない（翻訳）｜TechRacho by BPS株式会社](https://techracho.bpsinc.jp/hachi8833/2019_10_09/80851) (ちょっと古い記事ですが)
- [ローカルストレージは安全に使用できるのか？ \- Qiita](https://qiita.com/bricolageart/items/03328b8d92254d0aaa47)

**Comment by betachelsea** [comment]
追記・郵便番号単体では個人情報とみなさないようなので、このままでもOKとする、という判断でも良いです！ localStorageで扱う値には気をつけようということをお伝えしたかったです〜 :pray: ※もし今後拡張でお名前や住所などを組み合わせる発展系を検討されている場合は、避けた方が良いです。

**Comment by pachikuriii** [comment]
ご確認をありがとうございます！一旦、以下のように修正しました。

```json
{
  "started": true,
  "retirement_date": 2022-12-31, // 修正
  "retirement_reason": 1, 
  "re_employment": false,
  "age": 1, 
  "post_code": 1234567,
  "family": false,
  "emp_ins_last_two_years": 3, 
  "emp_ins_total": 2,  
  "health_ins_last_two_month": true,
  "health_ins_after_retirement": 2, 
  "tax": 2,
  "question": "q10" // 結果画面のときは"completed"に
}
```

> DBを使用しない == 永続化しない、という判断の様子かなと思って拝見しました 👀

おっしゃる通り、永続化はしないためLocal Strageを使おうと考えています。

> 退職予定日が 2022 、12 、 31 で分けて保存されていますが、日付として取り扱うならまとめておいたほうが取り出しやすくて簡便なのではないかと思いました。

まとめた方が日付の取り扱いが楽だろうな…と思ったので、まとめるようにしたいと思います🙆‍♀️

> post_code(郵便番号)が入っていますが、お住まいの番地なので、これを重要な個人情報と考えるか否かで取り扱いが変わってきそうです。自分はlocalStorageはあんまり安全性を信用していないので(※)郵便番号を取り扱うのはちょっと躊躇しそうです。郵便番号はresultのどの部分に影響するのか、もうちょっと仕様を深掘りして教えていただけますか？ 👀

追記も拝見しました😀
Local Strageで取り扱っていい情報/いけない情報についての意識が薄いままだったので、ご指摘いただきありがたいです！
そういった点について精査した上での判断が必要ですね。。。
今回の郵便番号の用途としてはユーザーに郵便番号を打ち込んでもらって、その郵便番号を管轄するハローワークを[自作のnpmパッケージ](https://www.npmjs.com/package/jp-hello-work)を使って導き出し、シミュレーターの結果画面に手続の際の行き先の情報として添えるためです。
自分でも調べてみましたが、住所が添えられた場合の郵便番号は個人情報になりそうですが、郵便番号単体だと個人の特定は難しそうなので今回はLocal Strageを使う形で進めたいと思います。


> question というのは現在表示している question 番号、という認識で良いですか？ result ページのとき、ここの値がどうなるか決めておいたほうが迷わずにすみそうです。

おっしゃる通り、questionは現在表示している question 番号を指します。resultのときはQ1-10までの解答がすべて埋まっていることを確認した上で"completed"としたらいいのかな…と考えているのですがいかがでしょうか…？

> (ペーパープロトタイプを見て) 「シュミレーション」という表記がありましたが、「シミュレーション」( simulation ) のためご注意ください〜 🙏

恥ずかしながら、ずっと「シュミレーション」だと思っておりました…修正しておきます！！！🙏

**Comment by pachikuriii** [comment]
@betachelsea 

ご確認をありがとうございます！一旦、以下のように修正しました。

```json
{
  "started": true,
  "retirement_date": 2022-12-31, // 修正
  "retirement_reason": 1, 
  "re_employment": false,
  "age": 1, 
  "post_code": 1234567,
  "family": false,
  "emp_ins_last_two_years": 3, 
  "emp_ins_total": 2,  
  "health_ins_last_two_month": true,
  "health_ins_after_retirement": 2, 
  "tax": 2,
  "question": "q10" // 結果画面のときは"completed"に
}
```

> DBを使用しない == 永続化しない、という判断の様子かなと思って拝見しました 👀

おっしゃる通り、永続化はしないためLocal Strageを使おうと考えています。

> 退職予定日が 2022 、12 、 31 で分けて保存されていますが、日付として取り扱うならまとめておいたほうが取り出しやすくて簡便なのではないかと思いました。

まとめた方が日付の取り扱いが楽だろうな…と思ったので、まとめるようにしたいと思います🙆‍♀️

> post_code(郵便番号)が入っていますが、お住まいの番地なので、これを重要な個人情報と考えるか否かで取り扱いが変わってきそうです。自分はlocalStorageはあんまり安全性を信用していないので(※)郵便番号を取り扱うのはちょっと躊躇しそうです。郵便番号はresultのどの部分に影響するのか、もうちょっと仕様を深掘りして教えていただけますか？ 👀

追記も拝見しました😀
Local Strageで取り扱っていい情報/いけない情報についての意識が薄いままだったので、ご指摘いただきありがたいです！
そういった点について精査した上での判断が必要ですね。。。
今回の郵便番号の用途としてはユーザーに郵便番号を打ち込んでもらって、その郵便番号を管轄するハローワークを[自作のnpmパッケージ](https://www.npmjs.com/package/jp-hello-work)を使って導き出し、シミュレーターの結果画面に手続の際の行き先の情報として添えるためです。
自分でも調べてみましたが、住所が添えられた場合の郵便番号は個人情報になりそうですが、郵便番号単体だと個人の特定は難しそうなので今回はLocal Strageを使う形で進めたいと思います。


> question というのは現在表示している question 番号、という認識で良いですか？ result ページのとき、ここの値がどうなるか決めておいたほうが迷わずにすみそうです。

おっしゃる通り、questionは現在表示している question 番号を指します。resultのときはQ1-10までの解答がすべて埋まっていることを確認した上で"completed"としたらいいのかな…と考えているのですがいかがでしょうか…？

> (ペーパープロトタイプを見て) 「シュミレーション」という表記がありましたが、「シミュレーション」( simulation ) のためご注意ください〜 🙏

恥ずかしながら、ずっと「シュミレーション」だと思っておりました…修正しておきます！！！🙏

**Comment by betachelsea** [comment]
@pachikuriii 

確認・修正ありがとうございました！

### 郵便番号
郵便番号活用 & 単体で使うなら問題ないとのことで、localStorageに保存で良さそうですね :ok_man: 

### question 項目

> resultのときはQ1-10までの解答がすべて埋まっていることを確認した上で"completed"としたらいいのかな…と考えている

こちら、独自の仕様になるので特にこうするのがベストですよというところも決まっていないもの…、ということになるので、pachikuriiiさんが「こうしよう！」と思った形で問題ないと思います :smile: 

このquestion項目のことに限らないかもしれませんが、イレギュラーな部分は少し考えながら進めていったほうが良さそうですね。このアプリの一番難しいところは回答の保持とページ遷移かもしれません。作っていくときは、ざっくり全体の流れが動くようになってから、ディティールにこだわるといった順番が、手戻りが少ないかもと思いました :eyes: (※ただの一意見なので、全然そうしなければならないというわけではないので、自由にやってくださいね！ :smile: )

想定しうるイレギュラーについて少し共有しておきます〜 :pray: 

- completedになってから最初のページ(path `/` )にアクセスされたらどうする?
- 1問目を飛ばしていきなり2問目(もしくは、3、4 など途中から) にアクセスされたらどうする?
- 結果ページにアクセスされた時に回答が足りなければどうする？(これはPOSTにすることで安易に発生しなくなるかもしれませんが、何かしらのバリデーションはした方が良いかもしれませんね)
- completedになった後に最初からやり直すときは既存データはどうする？ 全部消す？

うーん、もしかすると、順番とかにあまりこだわらず、最後の結果ページの時にだけバリデーションして、あとは各ページで回答済みor未回答 を出しておくだけでも十分かもしれませんね :thinking: 

こちらもリソース(URI)設計と同様、作ってみて初めて気づく問題点とか改善点がどんどん出てくると思うので、最初の想定にこだわりすぎず進めていただくのが良いかなと思っております！ファイトです〜 :muscle:

**Comment by pachikuriii** [comment]
一旦、現状でOKをいただいたのでcloseとします。

最終版のLocal Strageの構造で一旦進めつつ、作る中で変更したほうが実装しやすい、バリデーションした方がいい…と感じたところは都度改善しつつ進めていこうかと思います☺️
