### ISSUE TITLE
リソース(URI)設計

### ISSUE THREAD

**Issue by pachikuriii** [pachikuriii/yametara#4]
|  Method  |  PATH  | Description |  
| ---- | ---- |---- | 
|  GET |  /  | トップ画面の表示|  
|  GET |  /question |  ユーザー情報入力のための質問を表示、回答を入力してもらう（SPA） |  
|  GET |   /result |  /question でのユーザーの回答結果を元に最終結果を表示 |

**Comment by betachelsea** [comment]
ペーパープロトタイプ拝見しました！ :raised_hands: 答えていくだけで必要なことがわかって便利そうですね :+1: 

## `/question` ページについて

PATHですが、SPAであっても画面遷移があるので、各画面に明確なURLを設けたほうが(ルーティングがあったほうが)管理は楽そうだと思いました。
たとえば `/questions/1` などとすると q1 ページ の処理をする、というようなイメージです。ルーティングが無いと、1つの `/question` ページの処理の中で、if文かswitch文 でq1〜q8ページの出し分け処理をしなくてはならず、実装が煩雑になるかもと感じました。
こちら、一旦検討してみていただけますでしょうか？ (※検討した結果、やっぱり `/question` が適切だと思う、という結論に至ることもあるかと思います。それならそれで良いかと〜)

## `/result` ページについて

このページは `/question` の入力結果ありきのページなので、もし `/question` の一連の流れを実行せずにいきなり `GET /result` をされた場合、エラーもしくはトップに飛ばすなどの対処が必要そうですね。実行状況はlocalStorageに保存してあるとのことなので、GET でも問題なく動くとは思いますが、リクエストの性質としてはGET より POST のほうがイメージに近いかなと思いました。(通常のwebブラウザのアドレスバーに入力して飛ぶという操作はGETなので、`POST /result` という仕様にしておけば、心置きなく `GET /result` は「そんなページはありません」というものとして扱えます。) とはいえ、POSTの実装が面倒? ということはありそうなので、こちらについてもあくまで提案という形にしてみます。

↑上記を読んでみて、返信・ご意見いただけますでしょうか？ よろしくお願いします！ :pray:

**Comment by pachikuriii** [comment]
@betachelsea 

ご確認いただき、ありがとうございます。
フィードバックいただきまして、一旦以下のように修正しました。

|  Method  |  PATH  | Description |  
| ---- | ---- |---- | 
|  GET |  /  | トップ画面の表示|  
|  GET |  /questions/retirement|  今回の退職についての質問を表示、ユーザーが回答を入力 |  
|  GET |  /questions/job-after-retirement|  退職後の予定についての質問を表示、ユーザーが回答を入力 |  
|  GET |  /questions/user| ユーザー自身についての質問を表示、ユーザーが回答を入力） |  
|  GET |  /questions/family| 家族ついての質問を表示、ユーザーが回答を入力 |  
|  GET |  /questions/employment-insurance|  雇用保険についての質問を表示、ユーザーが回答を入力 |  
|  GET |  /questions/health-insurance|  健康保険についての質問を表示、ユーザーが回答を入力 |  
|  GET |  /questions/health-insurance-after-retirement| 退職後の健康保険についての質問を表示、ユーザーが回答を入力 |  
|  GET |  /questions/tax|  税金の支払いについての質問を表示、ユーザーが回答を入力 |  
|  POST |   /result |  /question でのユーザーの回答結果を元に最終結果を表示 |



> /question ページについて

Swiper.jsというライブラリを使って、q1〜q8のコンポーネントをを以下のように表示させていく想定でした。

![Image](https://user-images.githubusercontent.com/58751858/210780748-bdbcdc1b-1b5a-4696-a841-4eb0b80087f5.gif)

べーたさんからいただいたフィードバックを参考に、もう一度検討していたのですが、上記の想定で考えていたコードやライブラリの構造だとそれぞれの質問に応じてボタンを制御したい場合にかなり無理があるように感じました。
各画面では「質問」と「ユーザー情報の入力のための要素」、「画面遷移のためのボタン」はそれぞれに1セットずつ用意したほうがいいと思ったため、ルーティングを用意したいと思います💪🏻

> /result ページについて

おっしゃる通り、リクエストの性質としてはGET より POST のほうがイメージに近いですね…。
RESTのプラクティスを思い出しつつ…その方が違和感がないように思うのでPOST /resultで進めたいです。
POST /result にしてLocal Strageを元にユーザー情報をリクエストボディに含める形にしたらいいのかな？と思っています。

**Comment by pachikuriii** [comment]
一旦、現状でOKをいただいたのでcloseとします。

最終版のリソース設計で一旦進めつつ、作る中で`/question/1, /question/2`としたほうが実装しやすい…と感じたところは都度改善しつつ進めていこうかと思います。
